version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  mysqldb:
    image: mysql
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 21232619boom
      MYSQL_DATABASE: videogames
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  entervideogame:
    build: ./enterVideoGame/enterVideoGame
    restart: always
    container_name: entervideogame
    ports:
      - "8000:8000"
    depends_on:
      mysqldb:
        condition: service_healthy

  authenticationservice:
    build: ./authentication-service
    restart: always
    container_name: authenticationservice
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_healthy

  analytics-service:
    build: ./AnalyticsService/AnalyticsService
    restart: always
    container_name: analytics-service
    ports:
      - "9000:9000"
    depends_on:
      mysqldb:
        condition: service_healthy

  show-result:
    build: ./ShowGameResult/ShowGameResult
    restart: always
    container_name: show-result
    ports:
      - "9500:9500"
    depends_on:
      mysqldb:
        condition: service_healthy  